export const CHARACTERS = [
  ['skeleton','Skeleton Host','skeletal'],['spongebob-skeleton','SpongeBob Skeleton','cartoon-skeletal'],['robot','Cyber Robot','robotic'],['alien','Neon Alien','alien'],['ninja','Shadow Ninja','ninja'],['astronaut','Tech Astronaut','astronaut'],['hacker','Hooded Hacker','human'],['android','Android Host','android'],['cat','Cyber Cat','animal'],['dog','Cyber Dog','animal'],['pirate','Tech Pirate','human'],['wizard','Code Wizard','human'],['detective','Digital Detective','human'],['samurai','Neon Samurai','human'],['ghost','Glitch Ghost','spectral'],['business','AI Founder','human'],['anime','Anime Hero','stylized']
].map(([id,label,kind])=>({id,label,kind}));
export const TRENDS=['fast-cut hook','POV','before vs after','3 reasons','wait-for-it reveal','comment-bait question','myth vs fact','problem → solution','screen-record demo','day-in-the-life','storytime','challenge','reaction','top-3 list','cinematic reveal'];
export const POSES=['idle','talk','walk','point','tablet','turn','lean','celebrate','jump','dance'];
export function cleanText(v,max=12000){return String(v||'').replace(/[<>]/g,'').replace(/\s+/g,' ').trim().slice(0,max)}
export function splitScript(text,n=6){const s=cleanText(text,12000);if(!s)return[];const words=s.split(' '),out=[];for(let i=0;i<words.length&&out.length<n;){const take=Math.ceil((words.length-i)/(n-out.length));out.push(words.slice(i,i+take).join(' '));i+=take}return out}
export function deterministicPlan(text,duration,character,trend){
 const src=cleanText(text,5000), lines=splitScript(src,5), step=duration/Math.max(1,lines.length+1), shots=[];
 shots.push({start:0,end:Math.min(2,duration),camera:'close push',action:'establish character, direct eye focus, immediate hook',energy:'high',pose:'talk'});
 lines.forEach((line,i)=>{const start=Math.max(0,Math.min(duration,2+i*step)),end=Math.max(start+0.5,Math.min(duration,2+(i+1)*step));shots.push({start,end,camera:i%2?'three-quarter track':'medium track',action:line,energy:i===lines.length-1?'high':'medium',pose:/tablet|screen|app|html/i.test(line)?'tablet':/point|click/i.test(line)?'point':/dance/i.test(line)?'dance':'talk'})});
 shots.push({start:Math.max(0,duration-2),end:duration,camera:'hero pull back',action:'final pose and clear call to action',energy:'high',pose:'celebrate'});
 return {hook:'Open on motion, readable face, then move immediately into the user script.',shots:shots.filter(s=>s.end>s.start),motion:'articulated full-body pose transitions with weight shift and beat-aware timing',camera:'shot-specific perspective, push, track, orbit and pull-back cues',visualStyle:'cinematic vertical social video, deep blue studio, green HAxBRO accents',continuity:'lock character identity, wardrobe, screen placement and spatial direction across every shot',character,trend}
}
export function makePipeline(text,duration,character,trend){return {version:'2.0',stages:['input','semantic_director','shot_timeline','character_rig','scene_compositor','caption_layout','audio_mix','frame_recorder','quality_inspection','delivery'],contracts:{externalVideoGeneration:false,externalRenderer:false,deterministicFrames:true,vertical:true},timeline:deterministicPlan(text,duration,character,trend)}}