import { complete } from 'lib/core';

export const access = 'public';
export const methods = ['POST'];

const safe=(s)=>String(s||'').slice(0,12000);
const weatherLike=(s)=>/\b(weather|forecast|temperature|rain|humidity|climate)\b/i.test(s);
const calculatorLike=(s)=>/\b(calculator|calculate|calc)\b/i.test(s);
const gameLike=(s)=>/\b(game|games|arcade|runner|platformer|puzzle|quiz|snake|pong|tetris|shooter)\b/i.test(s);
const appType=(s)=>calculatorLike(s)?'calculator':weatherLike(s)?'weather':gameLike(s)?'game':'general';

async function weatherContext(city='Kolkata'){
  try{
    const geo=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=en&format=json`);
    const g=await geo.json(); const x=g.results?.[0];
    if(!x) return {city,available:false};
    const w=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${x.latitude}&longitude=${x.longitude}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&forecast_days=7&timezone=auto`);
    const j=await w.json(); return {city:x.name,latitude:x.latitude,longitude:x.longitude,current:j.current,daily:j.daily,source:'Open-Meteo'};
  }catch(e){return {city,available:false,error:'weather lookup failed'};}
}

function fallback(prompt,ctx){
  const type=appType(prompt);
  if(type==='calculator') return {name:'HAxBRO Calculator',summary:'A real four-function calculator with a polished keypad, expression display, clear/backspace, keyboard input, and responsive layout.',files:[
    {path:'index.html',content:`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>HAxBRO Calculator</title><link rel="stylesheet" href="style.css"></head><body><main class="calc"><div class="top"><span>HAxBRO</span><small>CALCULATOR</small></div><div class="display"><div id="expression"></div><strong id="value">0</strong></div><div class="keys"><button class="utility" data-action="clear">AC</button><button class="utility" data-action="back">⌫</button><button class="operator" data-key="%">%</button><button class="operator" data-key="/">÷</button><button data-key="7">7</button><button data-key="8">8</button><button data-key="9">9</button><button class="operator" data-key="*">×</button><button data-key="4">4</button><button data-key="5">5</button><button data-key="6">6</button><button class="operator" data-key="-">−</button><button data-key="1">1</button><button data-key="2">2</button><button data-key="3">3</button><button class="operator" data-key="+">+</button><button class="zero" data-key="0">0</button><button data-key=".">.</button><button class="equals" data-action="equals">=</button></div></main><script src="app.js"></script></body></html>`},
    {path:'style.css',content:`*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at 50% 10%,#17385c,#060d16 62%);color:#f5fbff;font-family:Inter,system-ui,sans-serif}.calc{width:min(390px,92vw);padding:18px;border:1px solid #294d6c;border-radius:28px;background:linear-gradient(160deg,#112a42,#091827);box-shadow:0 30px 90px #0009}.top{display:flex;justify-content:space-between;align-items:center;padding:4px 6px 14px}.top span{font-weight:800;letter-spacing:.12em;color:#42c7ff}.top small{font-size:9px;color:#7795ae;letter-spacing:.16em}.display{height:130px;padding:18px;border-radius:19px;background:#06111d;border:1px solid #203b53;display:flex;flex-direction:column;justify-content:end;text-align:right;overflow:hidden}.display #expression{height:25px;color:#66849e;font-size:13px;white-space:nowrap;overflow:hidden}.display strong{font-size:45px;line-height:1.1;font-weight:500;overflow:hidden;text-overflow:ellipsis}.keys{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:14px}.keys button{height:62px;border:1px solid #29445b;border-radius:16px;background:#142d44;color:#edf8ff;font-size:20px;font-weight:600;cursor:pointer;transition:.15s}.keys button:hover{background:#1b4667;transform:translateY(-1px)}.keys .utility{background:#1a3b53;color:#73d6ff}.keys .operator{background:#173d5b;color:#50caff}.keys .equals{background:linear-gradient(135deg,#315cff,#159bd8);border-color:transparent;box-shadow:0 10px 25px #159bd833}.keys .zero{grid-column:span 2}@media(max-width:420px){.calc{padding:14px;border-radius:22px}.keys{gap:7px}.keys button{height:56px;border-radius:13px}.display{height:115px}}`},
    {path:'app.js',content:`const value=document.querySelector('#value'),expr=document.querySelector('#expression');let cur='0',op=null,left=null,reset=false;function show(){value.textContent=cur}function inputDigit(x){if(reset||cur==='0'){cur=x;reset=false}else cur+=x;show()}function digit(x){if(x==='.')return cur.includes('.')?null:inputDigit(x);inputDigit(x)}function choose(o){left=Number(cur);op=o;expr.textContent=cur+' '+o;reset=true}function equals(){if(op===null)return;const r=Number(cur);let out=op==='+'?left+r:op==='-'?left-r:op==='*'?left*r:op==='/'?(r===0?NaN:left/r):left%r;expr.textContent=left+' '+op+' '+r+' =';cur=Number.isFinite(out)?String(Math.round(out*1e12)/1e12):'Error';op=null;reset=true;show()}document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{const k=b.dataset.key;if(/[0-9.]/.test(k))digit(k);else if(k==='%'){cur=String(Number(cur)/100);show()}else choose(k)});document.querySelector('[data-action=clear]').onclick=()=>{cur='0';op=null;left=null;expr.textContent='';reset=false;show()};document.querySelector('[data-action=back]').onclick=()=>{if(!reset)cur=cur.length>1?cur.slice(0,-1):'0';show()};document.querySelector('[data-action=equals]').onclick=equals;document.addEventListener('keydown',e=>{if(/[0-9.]/.test(e.key))digit(e.key);else if(['+','-','*','/'].includes(e.key))choose(e.key);else if(e.key==='Enter'||e.key==='=')equals();else if(e.key==='Escape')document.querySelector('[data-action=clear]').click();else if(e.key==='Backspace')document.querySelector('[data-action=back]').click()});`}
  ]};
  if(calculatorLike(prompt)) return {name:'HAxBRO Calculator',files:[
    {path:'index.html',content:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Calculator</title><link rel="stylesheet" href="style.css"></head><body><main><h1>Calculator</h1><input id="display" readonly><div id="keys"></div></main><script src="app.js"></script></body></html>'},
    {path:'style.css',content:'body{margin:0;min-height:100vh;display:grid;place-items:center;background:#07111f;color:#fff;font-family:system-ui}main{width:min(360px,90vw);padding:24px;background:#10263d;border:1px solid #2b5575;border-radius:20px}h1{color:#45c8ff}input{width:100%;box-sizing:border-box;padding:18px;margin-bottom:12px;border-radius:12px;border:1px solid #315674;background:#071827;color:#fff;font-size:28px;text-align:right}.keys{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}button{padding:18px;border:0;border-radius:12px;background:#173854;color:#fff;font-size:18px}button:hover{background:#1d75a8}'},
    {path:'app.js',content:'const d=document.querySelector("#display"),k=document.querySelector("#keys");k.className="keys";["7","8","9","/","4","5","6","*","1","2","3","-","0",".","=","+","C"].forEach(v=>{const b=document.createElement("button");b.textContent=v;b.onclick=()=>{if(v==="C")d.value="";else if(v==="="){try{d.value=Function("return "+d.value)()}catch{d.value="Error"}}else d.value+=v};k.appendChild(b)})'}
  ]};
  if(weatherLike(prompt)) return {name:'HAxBRO Weather',context:ctx,files:[
    {path:'index.html',content:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Weather</title><link rel="stylesheet" href="style.css"></head><body><main><header><b>HAxBRO WEATHER</b><span id="updated"></span></header><div class="search"><input id="city" value="Kolkata"><button onclick="load()">Search</button></div><section id="current"></section><h2>7-day forecast</h2><div id="days" class="days"></div></main><script src="app.js"></script></body></html>'},
    {path:'style.css',content:'body{margin:0;min-height:100vh;background:linear-gradient(135deg,#06101d,#12365a);color:#eef8ff;font-family:system-ui}main{width:min(950px,92%);margin:auto;padding:38px}.search{display:flex;gap:10px;margin:20px 0}.search input{flex:1;padding:14px;border-radius:12px;border:1px solid #315674;background:#0b1d30;color:white}.search button{padding:0 20px;border:0;border-radius:12px;background:#159bd8;color:white}.card,.day{background:#10263d;border:1px solid #294965;border-radius:18px;padding:22px}.hero{display:flex;justify-content:space-between;align-items:center}.temp{font-size:64px;margin:5px 0}.days{display:grid;grid-template-columns:repeat(7,1fr);gap:10px}.day{text-align:center}.day small{color:#9ab5cc}@media(max-width:700px){.days{grid-template-columns:repeat(2,1fr)}main{padding:22px}}'},
    {path:'app.js',content:`async function load(){const city=document.querySelector('#city').value||'Kolkata';const g=await fetch('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(city)+'&count=1&language=en&format=json').then(r=>r.json());const x=g.results?.[0];if(!x)return;const j=await fetch('https://api.open-meteo.com/v1/forecast?latitude='+x.latitude+'&longitude='+x.longitude+'&current=temperature_2m,relative_humidity_2m,apparent_temperature,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&forecast_days=7&timezone=auto').then(r=>r.json());document.querySelector('#updated').textContent='Updated '+new Date().toLocaleTimeString();document.querySelector('#current').innerHTML='<div class="card hero"><div><small>'+x.name+', '+(x.country||'')+'</small><div class="temp">'+Math.round(j.current.temperature_2m)+'°C</div><b>Feels like '+Math.round(j.current.apparent_temperature)+'°C</b><p>Humidity '+j.current.relative_humidity_2m+'% · Wind '+j.current.wind_speed_10m+' km/h</p></div><div style="font-size:60px">☁️</div></div>';document.querySelector('#days').innerHTML=j.daily.time.map((d,i)=>'<div class="day"><small>'+new Date(d).toLocaleDateString(undefined,{weekday:'short'})+'</small><h3>'+Math.round(j.daily.temperature_2m_max[i])+'° / '+Math.round(j.daily.temperature_2m_min[i])+'°</h3><small>'+j.daily.precipitation_probability_max[i]+'% rain</small></div>').join('')}load();`}
  ]};
  if(gameLike(prompt)) return {name:'HAxBRO Game',summary:'A playable browser game generated as a safe offline fallback.',files:[
    {path:'index.html',content:`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>HAxBRO Game</title><link rel="stylesheet" href="style.css"></head><body><main><header><h1>GAME</h1><span id="score">Score: 0</span></header><p>Move the player, collect the glowing targets, and beat your high score.</p><canvas id="game" width="720" height="420"></canvas><div class="controls"><button id="start">START / RESTART</button><span>Use ← → or A / D</span></div></main><script src="app.js"></script></body></html>`},
    {path:'style.css',content:'*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at 50% 10%,#17385c,#050a12 70%);color:#fff;font-family:system-ui,sans-serif}main{width:min(820px,94vw);padding:24px;border:1px solid #2c4e69;border-radius:24px;background:#0d1c2c;box-shadow:0 25px 80px #0008}header{display:flex;justify-content:space-between;align-items:center}h1{margin:0;color:#5dd6ff;letter-spacing:.15em}#score{font-weight:800}canvas{display:block;width:100%;height:auto;margin-top:16px;border-radius:16px;background:#06101b;border:1px solid #23435c}.controls{display:flex;gap:16px;align-items:center;margin-top:14px;flex-wrap:wrap}button{border:0;border-radius:12px;padding:12px 18px;background:#159bd8;color:#fff;font-weight:800;cursor:pointer}'},
    {path:'app.js',content:`const c=document.querySelector('#game'),x=c.getContext('2d'),scoreEl=document.querySelector('#score'),btn=document.querySelector('#start');let p={x:330,y:360,w:60,h:24},target={x:Math.random()*650+30,y:60},score=0,running=false,keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(['ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);function reset(){score=0;p.x=330;target={x:Math.random()*650+30,y:60};running=true;loop()}btn.onclick=reset;function loop(){if(!running)return;if(keys.arrowleft||keys.a)p.x-=6;if(keys.arrowright||keys.d)p.x+=6;p.x=Math.max(0,Math.min(c.width-p.w,p.x));target.y+=3.2;if(target.y>c.height+20){target={x:Math.random()*650+30,y:40};score=Math.max(0,score-1)}if(target.y>p.y-12&&target.y<p.y+p.h&&target.x>p.x-14&&target.x<p.x+p.w+14){score++;target={x:Math.random()*650+30,y:40}}scoreEl.textContent='Score: '+score;x.clearRect(0,0,c.width,c.height);x.fillStyle='#081522';x.fillRect(0,0,c.width,c.height);x.fillStyle='#5dd6ff';x.fillRect(p.x,p.y,p.w,p.h);x.beginPath();x.arc(target.x,target.y,12,0,Math.PI*2);x.fillStyle='#00d084';x.fill();x.fillStyle='#8aa9c0';x.font='16px system-ui';x.fillText('COLLECT',target.x-30,target.y-20);requestAnimationFrame(loop)}loop();`}
  ]};
  return {name:'HAxBRO Starter App',summary:'A functional responsive starter generated by HAxBRO.',files:[{path:'index.html',content:`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>HAxBRO App</title><link rel="stylesheet" href="style.css"></head><body><main><header><div><span>HAxBRO APP</span><h1>${safe(prompt).replace(/[<>]/g,'')}</h1></div><button id="action">START</button></header><section id="workspace"><div class="card">Your app workspace is ready.</div></section></main><script src="app.js"></script></body></html>`},{path:'style.css',content:'body{font-family:system-ui;background:radial-gradient(circle at top,#183b5a,#050a12 70%);color:#fff;margin:0;min-height:100vh;padding:30px}main{max-width:1000px;margin:auto;padding:28px;background:#0d1c2c;border:1px solid #294b66;border-radius:24px}header{display:flex;justify-content:space-between;gap:20px;align-items:center}h1{margin:.25em 0;font-size:clamp(28px,5vw,56px)}button{border:0;border-radius:12px;padding:12px 18px;background:#159bd8;color:#fff;font-weight:800}.card{margin-top:24px;padding:28px;background:#11283d;border-radius:18px}'},{path:'app.js',content:`const b=document.querySelector('#action'),w=document.querySelector('#workspace');b.onclick=()=>{b.textContent='RUNNING ✓';w.innerHTML='<div class="card"><h2>App is running</h2><p>Your HAxBRO-generated workspace is interactive and ready to extend.</p><button onclick="this.textContent=\'DONE ✓\'">TEST ACTION</button></div>'}`}]};
}

export default async function(req,res){
 const prompt=safe(req.body?.prompt); const username=safe(req.body?.username||'local-user',64); if(!prompt)return res.status(400).json({error:'Tell HAxBRO what app to build.'});
 let ctx=null; if(weatherLike(prompt)){const m=prompt.match(/(?:in|for|at)\s+([A-Za-z .'-]{2,40})/i);ctx=await weatherContext(m?.[1]||'Kolkata');}
 if(weatherLike(prompt)||calculatorLike(prompt)){
   const built=fallback(prompt,ctx);
   built.kai={version:'2.0',understood:weatherLike(prompt)?'Weather app':'Calculator app',researched:weatherLike(prompt)?'Open-Meteo current + 7-day weather structure':'Standard calculator UX',researchContext:ctx};
   return res.json(built);
 }
 try{
  const result=await complete({username:username,maxTokens:4200,system:`You are KAI 2.0, the HAxBRO App Builder. You are the actual builder, not a spec writer. The user's request must become a working web application. First understand the product and its normal UX, then write the complete files. NEVER return a plain text page for an app request unless the requested product itself is a text document. For games, create a genuinely playable game with controls, game state, scoring and restart. For AI apps, create a real chat-style workspace. For calculators, create a real keypad and calculation logic. For dashboards, create cards, navigation, charts/tables and working filters. For weather, create search/location, current conditions and forecast. For editors, create editing controls and a working surface. For commerce, create products, cart and checkout-like interactions. Use polished responsive UI, realistic states, and useful interactions. Return ONLY valid JSON: {"name":"...","summary":"...","files":[{"path":"index.html","content":"..."},{"path":"style.css","content":"..."},{"path":"app.js","content":"..."}]}. Keep the app self-contained and client-side unless the request truly requires a backend. Do not return a plan, markdown fences, or prose outside JSON. You are KAI; the App Maker UI should be able to say that KAI understood and built the app.`,prompt:`USER REQUEST:\n${prompt}\n\nRESEARCH CONTEXT:\n${JSON.stringify(ctx||{})}`,history:''});
  let parsed; try{
    const raw=String(result.text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');
    parsed=JSON.parse(raw);
  }catch{
    parsed=null;
  }
  if(!parsed?.files?.length) return res.json(fallback(prompt,ctx));
  return res.json(parsed);
 }catch(e){console.error(e);return res.json(fallback(prompt,ctx));}
}