import { complete } from 'lib/kai';
import { storage } from 'hatchable';

export const access = 'user';
export const methods = ['POST'];

const enc = new TextEncoder();
const bytes = s => enc.encode(String(s));
const u32 = n => new Uint8Array([n & 255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]);
const u16 = n => new Uint8Array([n & 255,(n>>>8)&255]);
function concat(parts){let n=0;for(const p of parts)n+=p.length;const out=new Uint8Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function crc32(data){let c=0xffffffff;for(const b of data){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
function zipStore(files){
  const local=[],central=[];let offset=0;
  for(const f of files){const name=bytes(f.name),data=f.data,crc=crc32(data);const h=concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name]);local.push(h,data);central.push(concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=h.length+data.length}
  const cd=concat(central),body=concat(local),eocd=concat([u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(cd.length),u32(body.length),u16(0)]);return concat([body,cd,eocd])
}
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function pdfEscape(s){return String(s??'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function makePdf(title,body){
  const lines=[String(title||'HAxBRO Document'),'',...String(body||'').split(/\r?\n/)];
  const pages=[];let page=[];for(const raw of lines){let line=raw;while(line.length>92){page.push(line.slice(0,92));line=line.slice(92)}page.push(line);if(page.length>=48){pages.push(page);page=[]}}if(page.length)pages.push(page);if(!pages.length)pages.push(['HAxBRO']);
  const objs=[];const add=x=>{objs.push(x);return objs.length};
  const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');const pagesObj=add(null);const pageIds=[];
  for(const p of pages){let stream='BT\n/F1 11 Tf\n50 760 Td\n';for(const line of p){stream+=`(${pdfEscape(line)}) Tj\n0 -15 Td\n`}stream+='ET';const content=add(`<< /Length ${bytes(stream).length} >>\nstream\n${stream}\nendstream`);const pg=add(`<< /Type /Page /Parent ${pagesObj} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${content} 0 R >>`);pageIds.push(pg)}
  objs[pagesObj-1]=`<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(x=>x+' 0 R').join(' ')}] >>`;const catalog=add(`<< /Type /Catalog /Pages ${pagesObj} 0 R >>`);
  let out='%PDF-1.4\n%âãÏÓ\n',offs=[0];for(let i=0;i<objs.length;i++){offs[i+1]=bytes(out).length;out+=`${i+1} 0 obj\n${objs[i]}\nendobj\n`}const xref=bytes(out).length;out+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offs.length;i++)out+=String(offs[i]).padStart(10,'0')+' 00000 n \n';out+=`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return bytes(out)
}
function makePptx(title,slides){
  const safeSlides=(slides?.length?slides:[{title,body:''}]).slice(0,30);const files=[];
  files.push({name:'[Content_Types].xml',data:bytes(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>${safeSlides.map((_,i)=>`<Override PartName="/ppt/slides/slide${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`).join('')}</Types>`)});
  files.push({name:'_rels/.rels',data:bytes(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/></Relationships>`)});
  const presRels=safeSlides.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${i+1}.xml"/>`).join('');
  files.push({name:'ppt/_rels/presentation.xml.rels',data:bytes(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${presRels}<Relationship Id="rId${safeSlides.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/></Relationships>`)});
  files.push({name:'ppt/presentation.xml',data:bytes(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId${safeSlides.length+1}"/></p:sldMasterIdLst><p:sldIdLst>${safeSlides.map((_,i)=>`<p:sldId id="${256+i}" r:id="rId${i+1}"/>`).join('')}</p:sldIdLst><p:sldSz cx="12192000" cy="6858000" type="screen16x9"/><p:notesSz cx="6858000" cy="9144000"/><p:defaultTextStyle/><p:showPr/></p:presentation>`)});
  files.push({name:'ppt/slideMasters/slideMaster1.xml',data:bytes(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" preserve="1"><p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val="F8FAFC"/></a:solidFill><a:effectLst/></p:bgPr></p:bg><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree></p:cSld><p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/><p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId1"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>`)});
  files.push({name:'ppt/slideMasters/_rels/slideMaster1.xml.rels',data:bytes(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/></Relationships>`)});
  files.push({name:'ppt/slideLayouts/slideLayout1.xml',data:bytes(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="title" matchingName="Title Slide" preserve="1"><p:cSld name="Title Slide"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`)});
  files.push({name:'ppt/slideLayouts/_rels/slideLayout1.xml.rels',data:bytes(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/></Relationships>`)});
  files.push({name:'ppt/theme/theme1.xml',data:bytes(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="HAxBRO"><a:themeElements><a:clrScheme name="HAxBRO"><a:dk1><a:sysClr val="windowText" lastClr="000000"/></a:dk1><a:lt1><a:sysClr val="window" lastClr="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="1F2937"/></a:dk2><a:lt2><a:srgbClr val="F8FAFC"/></a:lt2><a:accent1><a:srgbClr val="315CFF"/></a:accent1><a:accent2><a:srgbClr val="00A86B"/></a:accent2><a:accent3><a:srgbClr val="EF4444"/></a:accent3><a:accent4><a:srgbClr val="F59E0B"/></a:accent4><a:accent5><a:srgbClr val="7C3AED"/></a:accent5><a:accent6><a:srgbClr val="0EA5E9"/></a:accent6><a:hlink><a:srgbClr val="315CFF"/></a:hlink><a:folHlink><a:srgbClr val="7C3AED"/></a:folHlink></a:clrScheme><a:fontScheme name="HAxBRO"><a:majorFont><a:latin typeface="Aptos Display"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont><a:minorFont><a:latin typeface="Aptos"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont></a:fontScheme><a:fmtScheme name="HAxBRO"><a:fillStyleLst><a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill><a:solidFill><a:srgbClr val="F8FAFC"/></a:solidFill><a:solidFill><a:srgbClr val="315CFF"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w="12700"><a:solidFill><a:srgbClr val="CBD5E1"/></a:solidFill><a:prstDash val="solid"/></a:ln><a:ln w="25400"><a:solidFill><a:srgbClr val="315CFF"/></a:solidFill><a:prstDash val="solid"/></a:ln><a:ln w="38100"><a:solidFill><a:srgbClr val="00A86B"/></a:solidFill><a:prstDash val="solid"/></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill><a:solidFill><a:srgbClr val="F8FAFC"/></a:solidFill><a:solidFill><a:srgbClr val="E8F0FF"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements><a:objectDefaults/><a:extraClrSchemeLst/></a:theme>`)});
  for(let i=0;i<safeSlides.length;i++){const s=safeSlides[i],rel=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>`;files.push({name:`ppt/slides/_rels/slide${i+1}.xml.rels`,data:bytes(rel)});const body=String(s.body||'').split(/\r?\n/).slice(0,18);const paras=body.map(x=>`<a:p><a:r><a:rPr lang="en-US" sz="1800"/><a:t>${esc(x)}</a:t></a:r><a:endParaRPr lang="en-US"/></a:p>`).join('');files.push({name:`ppt/slides/slide${i+1}.xml`,data:bytes(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val="F8FAFC"/></a:solidFill><a:effectLst/></p:bgPr></p:bg><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:sp><p:nvSpPr><p:cNvPr id="4" name="HAxBRO Accent"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="720000" y="280000"/><a:ext cx="10800000" cy="90000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="315CFF"/></a:solidFill><a:ln><a:noFill/></a:ln></p:spPr></p:sp><p:sp><p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="720000" y="400000"/><a:ext cx="10800000" cy="900000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US" sz="2800" b="1"/><a:t>${esc(s.title||'HAxBRO')}</a:t></a:r><a:endParaRPr lang="en-US"/></a:p></p:txBody></p:sp><p:sp><p:nvSpPr><p:cNvPr id="3" name="Body"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="720000" y="1500000"/><a:ext cx="10800000" cy="5000000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill><a:ln><a:solidFill><a:srgbClr val="D7E3F4"/></a:solidFill><a:prstDash val="solid"/></a:ln></p:spPr><p:txBody><a:bodyPr wrap="square"/><a:lstStyle/>${paras}</p:txBody></p:sp></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`)});}
  return zipStore(files)
}
function makeZip(files){return zipStore((files||[]).slice(0,40).map(f=>({name:String(f.path||f.name||'file.txt').replace(/^\/+/,''),data:bytes(String(f.content??''))})).filter(f=>f.name))}
function extFor(type){return type==='pptx'?'pptx':type==='pdf'?'pdf':'zip'}
export default async function(req,res){
  const prompt=String(req.body?.prompt||'').trim();let type=String(req.body?.type||'').toLowerCase();if(!prompt)return res.status(400).json({error:'Describe the file you want HAxBRO to create.'});if(!['pdf','ppt','pptx','powerpoint','zip'].includes(type))return res.status(400).json({error:'Supported file types: PDF, PPTX, ZIP.'});if(type==='ppt'||type==='powerpoint')type='pptx';
  try{
    const instruction=type==='pdf'?`Return JSON only: {"title":"...","body":"..."}. Create polished document content for this request. No markdown fences.`:type==='pptx'?`Return JSON only: {"title":"...","slides":[{"title":"...","body":"line 1\\nline 2"}]}. Create a useful professional presentation with 4-12 slides. Design every slide intentionally: vary title/section/content roles, use concise bullets, strong hierarchy, visual storytelling, and clear HAxBRO branding. The renderer will apply real fills, accent bars, typography, spacing, and slide-specific visual treatment. Never output a plain text-only deck. No markdown fences.`:`Return JSON only: {"name":"...","files":[{"path":"...","content":"..."}]}. Create a complete useful ZIP bundle for this request. Include all necessary text/code/assets-as-text files. No markdown fences.`;
    const result=await complete({system:`You are HAxBRO File Creator. You create the actual requested artifact, not instructions. ${instruction}`,prompt,maxTokens:6500,history:''});
    let raw=String(result.text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');let data;try{data=JSON.parse(raw)}catch{const a=raw.indexOf('{'),b=raw.lastIndexOf('}');if(a>=0&&b>a){try{data=JSON.parse(raw.slice(a,b+1))}catch{data=null}}if(!data)return res.status(502).json({error:'The file content could not be structured safely. Please try again.'})}
    let bin,name,mime;if(type==='pdf'){bin=makePdf(data.title||'HAxBRO Document',data.body||'');name=(data.title||'haxbro-document').replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()+'.pdf';mime='application/pdf'}else if(type==='pptx'){bin=makePptx(data.title||'HAxBRO Presentation',data.slides||[]);name=(data.title||'haxbro-presentation').replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()+'.pptx';mime='application/vnd.openxmlformats-officedocument.presentationml.presentation'}else{bin=makeZip(data.files||[]);name=(data.name||'haxbro-bundle').replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()+'.zip';mime='application/zip'}
    const key=`artifacts/${Date.now()}-${Math.random().toString(36).slice(2)}-${name}`;const url=await storage.put(key,bin,mime);return res.json({ok:true,type,name,url,size:bin.length,createdBy:'HAxBRO File Creator',provider:result.provider,model:result.model})
  }catch(e){console.error('File creator error',e);return res.status(503).json({error:'HAxBRO could not create that file right now. Please try again.'})}
}